namespace BloomersMicrovixIntegrations.Domain.Entities.Ecommerce
{
    public class LinxMovimento
    {
        public DateTime lastupdateon { get; set; }
        public string? portal { get; set; }
        public string? cnpj_emp { get; set; }
        public string? transacao { get; set; }
        public string? usuario { get; set; }
        public string? documento { get; set; }
        public string? chave_nf { get; set; }
        public string? ecf { get; set; }
        public string? numero_serie_ecf { get; set; }
        public string? modelo_nf { get; set; }
        public string? data_documento { get; set; }
        public string? data_lancamento { get; set; }
        public string? codigo_cliente { get; set; }
        public string? serie { get; set; }
        public string? desc_cfop { get; set; }
        public string? id_cfop { get; set; }
        public string? cod_vendedor { get; set; }
        public string? quantidade { get; set; }
        public string? preco_custo { get; set; }
        public string? valor_liquido { get; set; }
        public string? desconto { get; set; }
        public string? cst_icms { get; set; }
        public string? cst_pis { get; set; }
        public string? cst_cofins { get; set; }
        public string? cst_ipi { get; set; }
        public string? valor_icms { get; set; }
        public string? aliquota_icms { get; set; }
        public string? base_icms { get; set; }
        public string? valor_pis { get; set; }
        public string? aliquota_pis { get; set; }
        public string? base_pis { get; set; }
        public string? valor_cofins { get; set; }
        public string? aliquota_cofins { get; set; }
        public string? base_cofins { get; set; }
        public string? valor_icms_st { get; set; }
        public string? aliquota_icms_st { get; set; }
        public string? base_icms_st { get; set; }
        public string? valor_ipi { get; set; }
        public string? aliquota_ipi { get; set; }
        public string? base_ipi { get; set; }
        public string? valor_total { get; set; }
        public string? forma_dinheiro { get; set; }
        public string? total_dinheiro { get; set; }
        public string? forma_cheque { get; set; }
        public string? total_cheque { get; set; }
        public string? forma_cartao { get; set; }
        public string? total_cartao { get; set; }
        public string? forma_crediario { get; set; }
        public string? total_crediario { get; set; }
        public string? forma_convenio { get; set; }
        public string? total_convenio { get; set; }
        public string? frete { get; set; }
        public string? operacao { get; set; }
        public string? tipo_transacao { get; set; }
        public string? cod_produto { get; set; }
        public string? cod_barra { get; set; }
        public string? cancelado { get; set; }
        public string? excluido { get; set; }
        public string? soma_relatorio { get; set; }
        public Guid identificador { get; set; }
        public string? deposito { get; set; }
        public string? obs { get; set; }
        public string? preco_unitario { get; set; }
        public string? hora_lancamento { get; set; }
        public string? natureza_operacao { get; set; }
        public string? tabela_preco { get; set; }
        public string? nome_tabela_preco { get; set; }
        public string? cod_sefaz_situacao { get; set; }
        public string? desc_sefaz_situacao { get; set; }
        public string? protocolo_aut_nfe { get; set; }
        public string? dt_update { get; set; }
        public string? forma_cheque_prazo { get; set; }
        public string? total_cheque_prazo { get; set; }
        public string? cod_natureza_operacao { get; set; }
        public string? preco_tabela_epoca { get; set; }
        public string? desconto_total_item { get; set; }
        public string? conferido { get; set; }
        public string? transacao_pedido_venda { get; set; }
        public string? codigo_modelo_nf { get; set; }
        public string? acrescimo { get; set; }
        public string? mob_checkout { get; set; }
        public string? aliquota_iss { get; set; }
        public string? base_iss { get; set; }
        public string? ordem { get; set; }
        public string? codigo_rotina_origem { get; set; }
        public string? timestamp { get; set; }
        public string? troco { get; set; }
        public string? transportador { get; set; }
        public string? icms_aliquota_desonerado { get; set; }
        public string? icms_valor_desonerado_item { get; set; }
        public string? empresa { get; set; }
        public string? desconto_item { get; set; }
        public string? aliq_iss { get; set; }
        public string? iss_base_item { get; set; }
        public string? despesas { get; set; }
        public string? seguro_total_item { get; set; }
        public string? acrescimo_total_item { get; set; }
        public string? despesas_total_item { get; set; }
        public string? forma_pix { get; set; }
        public string? total_pix { get; set; }
        public string? forma_deposito_bancario { get; set; }
        public string? total_deposito_bancario { get; set; }
    }
}
